### ISSUE TITLE
Nexe configuration error

### ISSUE THREAD

**Issue by rojhan** [crcn/nexe#81] opened 2014-09-26 08:48 UTC
We try nexe 32 bit and 64 bit on windows but we take same error.Error is in file that created file by nexe .when we run node nexe.js on vs2012 x64 command prompt we take this error 
![nexeerror](https://cloud.githubusercontent.com/assets/8926434/4420583/575d11fc-457b-11e4-8353-bafff004bed3.png)

And result.exe doens't creat.

how can ı solve this error ?

**Comment by RainbowDashDC** [comment] 2015-02-14 03:58
I cannot reproduce this either. Using VS 2013 with node 0.10.33

**Comment by RainbowDashDC** [comment] 2015-02-15 21:06
Closing because this would be an issue with Node.js not nexe.

**Closed by RainbowDashDC** 2015-02-15 21:06 UTC
Labels: more-information-needed, needs-reproduction
