### ISSUE TITLE
tar: \tmp\nexe\\latest: Cannot chdir: No such file or directory

### ISSUE THREAD

**Issue by fanrl** [crcn/nexe#54] opened 2014-05-28 08:42 UTC
I use:
node v0.10.28
express 4.2.0

do step:
step 1:
npm install nexe

step 2:
nexe -i ./bin/www -o 1.exe

----> tar -xf \tmp\nexe\latest\node-latest.tar.gz -C \tmp\nexe\latest
tar: \tmp\nexe\\latest: Cannot chdir: No such file or directory
tar: Error is not recoverable: exiting now
stdout: Broken pipe

**Comment by RainbowDashDC** [comment] 2015-02-15 04:03
Duplicate of #41 which has been fixed.

**Closed by RainbowDashDC** 2015-02-15 04:03 UTC
