### ISSUE TITLE
fail to start

### ISSUE THREAD

**Issue by shaylang** [crcn/nexe#66] opened 2014-07-30 14:56 UTC
nexe.js:3560
  "application/1d-interleaved-parityfec": [],
                                        ^
SyntaxError: Unexpected token :
    at NativeModule.compile (node.js:899:14)
    at Function.NativeModule.require (node.js:869:18)
    at Function.Module._load (module.js:297:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at [eval]:1:1
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:539:25)
    at startup (node.js:83:7)

**Comment by Smile42RU** [comment] 2015-01-05 10:15
@shaylang any updates? You have workaround for it?

**Comment by LorenzGardner** [comment] 2015-01-06 00:30
I believe this is caused by encountering a native module, which is not support in the bundling process. There are workarounds to get a native module working.

For instance, in my app i use node-usb.

1) Make sure the dep is not bundled.

So instead of doing a require("usb"), I do var x = "usb"; require(x); 
This just turns it into a "dynamic" require and the blunder doesn't know about it.

2) You need to install / copy the dep to a node_module folder along side your executable

So in my case i needed to copy the node_module/usb folder to my deployed system (this is of course platform dependent and thus you need to copy the folder from them same os as you are deploying too, and you can instead use a "npm install usb")

3) On windows you may have to name your exe "node.exe",

The native module may llnk back to the node executable by name and as your packaged app is now the node app you have to make that link work. (this was required for node-usb)

I was then able to deploy by app along with the native module (in the node_module/usb folder) and it ran on a deployed system. 

This of course is a bit messy.

**Comment by Smile42RU** [comment] 2015-01-07 22:46
@LorenzGardner it happens because one of files in module seems like this:

{ "var": "value" }

As you see it's just valid JSON, but module working with this file as JSON object, then nexe just implement it as plain-text without return statement.

That it.

**Comment by Smile42RU** [comment] 2015-01-07 22:47
Well, just notification: this trouble related with express framework.

**Comment by LorenzGardner** [comment] 2015-01-07 23:01
You are referring to the fact that a require('foo.json') doesn't work in the release version of nexe. This has been added (#85), and please try against the master branch to see if that fixes the issue.

nexe.js is the file generated by the bundler, and it appears that something went wrong. I'm not sure there is enough info in the OP to know what exactly.

Hopefully @shaylang can post some lines of code around the line 3560. (note the nexe.js will be in the lib dir of the unzipped node project in the temp dir)

**Comment by RainbowDashDC** [comment] 2015-02-15 04:02
Seems to be fixed currently, if I'm wrong please re-open.

**Closed by RainbowDashDC** 2015-02-15 04:02 UTC
Labels: more-information-needed, needs-reproduction
