### ISSUE TITLE
Error when trying to compile

### ISSUE THREAD

**Issue by leearmstrong** [crcn/nexe#37] opened 2013-12-24 09:21 UTC
I get the following error.  

Error: Cannot find module './lib-cov/express'

Looking in the path it is after there is a /lib/express but no lib-cov/

Any ideas what is going wrong there?

**Comment by RainbowDashDC** [comment] 2015-02-15 04:21
This should be fixed as from a pervious commit, if not please re-open.

**Closed by RainbowDashDC** 2015-02-15 04:21 UTC

**Comment by Name-less** [comment] 2016-01-30 10:18
I have the same issue, is the issue resolved ?

**Comment by jaredallard** [comment] 2016-02-01 04:10
@Name-less Hi! Got some reproducing code? nexe compile args? Etc?

If this is just express, I cannot reproduce it as I have express 3.x.x compiling!

**Comment by Name-less** [comment] 2016-02-01 08:25
I finally replace index.js of express module by : 

`module.exports = require('./lib/express');`

nexe config is (with express 4.13.1) :

`"nexe": {
    "input": "./bin/www",
    "output": "nexe^$",
    "temp": "src",
    "runtime": {
        "framework": "node",
        "version": "5.5.0",
        "js-flags": "--use_strict",
        "ignoreFlags": true
    } `
